import time
import datetime as dt
import pandas as pd
from request import connect_DWH_CoSo
from win32com.client import Dispatch

def run():

    def __checkRun(t: dt.datetime):
        if t.weekday() in (5,6):  # thứ 7, CN
            return False
        if dt.time(8,0,0) <= t.time() <= dt.time(16,1,0):  # Chạy ca sáng
            return True
        # Note: thêm 1 phút để tránh bug (do cài sleep)
        return False

    
    while __checkRun(dt.datetime.now()):

        now = dt.datetime.now()
        orderTable = pd.read_sql(
            """
            SELECT 
                [TenKhachHang], 
                [SoTienChuyen], 
                [NganHangThuHuong]
            FROM [VCI1104] 
            -- quét 15s/lần, check trong 10s gần nhất
            WHERE [ThoiGianGhiNhan] >= DATEADD(SECOND,-10,GETDATE())
                AND [SoTienChuyen] >= 10e9
            """,
        connect_DWH_CoSo
        )
        orderTable['SoTienChuyen'] = orderTable['SoTienChuyen'].map(lambda num: f"{int(num):,}")

        outlook = Dispatch('outlook.application')
        mail = outlook.CreateItem(0)
        mail.To = 'nhungo@phs.vn; thaonguyenthanh@phs.vn; vanho@phs.vn; phuongtranbuu@phs.vn'
        mail.Subject = f"Lệnh Rút Tiền Trên 10 Tỷ"
        if not orderTable.empty: # có lệnh lớn
            htmlTable = orderTable.to_html(index=False,header=True).replace("\\n","<br>")
            htmlBody = f"""
            <html>
                <head></head>
                <body>
                    {htmlTable}
                    <p style="font-family:Times New Roman; font-size:90%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
            """
            mail.HTMLBody = htmlBody
            mail.Send()
            print(f"{now.strftime('%H:%M:%S %d.%m.%Y')}\n{orderTable}\n=====================")
        else:
            print(f"{now.strftime('%H:%M:%S %d.%m.%Y')}\nKhông có lệnh lớn\n=====================")

        time.sleep(15)

if __name__ == '__main__':
    run()

