from datawarehouse import *
from automation.finance import getBankData


class BankFailedException(Exception):
    pass

def GetDataMonitor(func):

    def wrapper(*args):
        bank = args[0]
        run_date = args[1].strftime('%d.%m.%Y')
        outlook = Dispatch('outlook.application')
        mail = outlook.CreateItem(0)
        mail.To = 'hiepdang@phs.vn'
        try:
            table = func(*args)
            mail.Subject = f"BankCurrentBalance.{bank} for {run_date} Run Successfully"
            body = f"""
                <html>
                    <head></head>
                    <body>
                        <p style="font-family:Times New Roman; font-size:90%"><i>
                            -- Generated by Reporting System
                        </i></p>
                    </body>
                </html>
                """
            mail.HTMLBody = body
            mail.Send()
        except (Exception,):
            mail.Subject = f"BankCurrentBalance.{bank} for {run_date} Got Error"
            traceback_message = traceback.format_exc()
            body = f"""
                <html>
                    <head></head>
                    <body>
                        <p style="font-family:Consolas; font-size:90%">
                        {traceback_message}
                        </p>
                        <p style="font-family:Times New Roman; font-size:90%"><i>
                            -- Generated by Reporting System
                        </i></p>
                    </body>
                </html>
                """
            mail.HTMLBody = body
            mail.Send()
            raise BankFailedException(f"{bank} failed on {run_date}")
        return table

    return wrapper




def run(bank,fromDate,toDate):

    @GetDataMonitor
    def getData(bank,fromDate,toDate):
        bankObject = eval(f'getBankData.{bank}')
        return bankObject(fromDate,toDate).TienGuiThanhToan()

    for _ in range(2): # chạy tối đa 2 lần
        try:
            balanceTable = getData(bank,fromDate,toDate)
            INSERT(connect_DWH_CoSo,'BankCurrentBalance',balanceTable)
            checkCols = ['BankCurrentBalance','Date','AccountNumber','Currency']
            DROP_DUPLICATES(connect_DWH_CoSo,*checkCols)  # xóa dòng trùng nhau
            break
        except (Exception,):
            pass

