from datawarehouse import *
from automation.finance import getBankData


class BankFailedException(Exception):
    pass

def GetDataMonitor(func):

    def wrapper(*args,**kwargs):
        bank = args[0]
        run_date = args[1].strftime('%d.%m.%Y')
        outlook = Dispatch('outlook.application')
        mail = outlook.CreateItem(0)
        mail.To = 'hiepdang@phs.vn'
        try:
            func(*args,**kwargs)
            mail.Subject = f"BankCurrentBalance.{bank} for {run_date} Done"
            body = f"""
                <html>
                    <head></head>
                    <body>
                        <p style="font-family:Times New Roman; font-size:90%"><i>
                            -- Generated by Reporting System
                        </i></p>
                    </body>
                </html>
                """
            mail.HTMLBody = body
            mail.Send()
        except (Exception,):
            mail.Subject = f"BankCurrentBalance.{bank} for {run_date} Failed"
            traceback_message = traceback.format_exc()
            body = f"""
                <html>
                    <head></head>
                    <body>
                        <p style="font-family:Consolas; font-size:90%">
                        {traceback_message}
                        </p>
                        <p style="font-family:Times New Roman; font-size:90%"><i>
                            -- Generated by Reporting System
                        </i></p>
                    </body>
                </html>
                """
            mail.HTMLBody = body
            mail.Send()
            raise BankFailedException(f"{bank} failed on {run_date}")

    return wrapper


@GetDataMonitor
def run(bank,fromDate,toDate,debug=True):

    if bank == 'BIDV':
        bankObject = getBankData.BIDV(fromDate,toDate,debug).Login()
    elif bank == 'EIB':
        bankObject = getBankData.EIB(fromDate,toDate,debug).Login()
    elif bank == 'IVB':
        bankObject = getBankData.IVB(fromDate,toDate,debug).Login()
    elif bank == 'VTB':
        bankObject = getBankData.VTB(fromDate,toDate,debug).Login()
    elif bank == 'VCB':
        bankObject = getBankData.VCB(fromDate,toDate,debug).Login()
    elif bank == 'OCB':
        bankObject = getBankData.OCB(fromDate,toDate,debug).Login()
    else:
        raise ValueError(f'Invalid bank name: {bank}')

    zipObject = zip(
        [bankObject.TienGuiThanhToan,bankObject.TienGuiKyHan],
        ['BankCurrentBalance','BankDepositBalance'],
        [['Date','Bank','AccountNumber','Currency'],['Date','Bank','AccountNumber','IssueDate','ExpireDate','Currency']]
    )
    for func, dwhTable, checkCols in zipObject:
        print(func.__name__)
        bankObject, balanceTable = func()
        fromDateString = fromDate.strftime('%Y-%m-%d')
        toDateString = toDate.strftime('%Y-%m-%d')
        DELETE(connect_DWH_CoSo,dwhTable,'W')
        DELETE(connect_DWH_CoSo,dwhTable,f"""WHERE [Date] BETWEEN '{fromDateString}' AND '{toDateString}' AND [Bank] = '{bank}'""")
        INSERT(connect_DWH_CoSo,dwhTable,balanceTable)

    del bankObject # destroy the object to close opening Chrome driver (call __del__ magic method)